# Generated by Django 4.0.4 on 2022-05-05 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='article_author',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author_bio',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
