# Generated by Django 4.0.4 on 2022-05-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0006_rename_category_blogpost_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
    ]
