# Generated by Django 4.0.4 on 2022-05-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0007_remove_blogpost_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='author_name',
            new_name='author',
        ),
    ]
