# Generated by Django 4.0.4 on 2022-05-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0008_rename_author_name_blogpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='../media/undraw_super_woman_dv0y_GTj3dqq.jpg', upload_to=''),
        ),
    ]
