# Generated by Django 4.0.4 on 2022-05-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0012_alter_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='./media/undraw_super_woman_dv0y_8VXFjyw.jpg', upload_to=''),
        ),
    ]
