# Generated by Django 4.0.4 on 2022-05-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
